on:
  pull_request:
    branches:
      - master

jobs:
  Install:
    uses: ./.github/workflows/intall-deps.yml
  Lint:
    uses: ./.github/workflows/lint.yml
  Unit_Test:
    uses: ./.github/workflows/run-unit-tests.yml