on:
  pull_request:
    branches:
      - master

jobs:
  Install:
    uses: ./.github/workflows/intall-deps.yml@ci/basic-ci-cd
  Lint:
    uses: ./.github/workflows/lint.yml@ci/basic-ci-cd
  Unit_Test:
    uses: ./.github/workflows/run-unit-tests.yml@ci/basic-ci-cd